# vim:ft=kitty
## name: forestfrog
## author: frog
## license: UPL-1.0
## blurb: A deep forest green theme for kitty

# General
foreground                      #AFC2B1
background                      #0C120D
selection_foreground            #0C120D
selection_background            #4E744F

# Cursor
cursor                          #78A47A
cursor_text_color               #0C120D

# Links
url_color                       #6FAF78

# Borders
active_border_color             #4E744F
inactive_border_color           #263629
bell_border_color               #789052
visual_bell_color               #789052

# Tabs
active_tab_foreground           #AFC2B1
active_tab_background           #0C120D
inactive_tab_foreground         #708373
inactive_tab_background         #1C2A1E
tab_bar_background              #0C120D
tab_bar_margin_color            #0C120D

# Colors
color0 #0C120D
color8 #354536

color1 #B85C5C
color9 #D47777

color2 #527F58
color10 #72A878

color3 #927C4D
color11 #B49B61

color4 #526F80
color12 #718FA0

color5 #765F80
color13 #967BA0

color6 #4F7F73
color14 #6FA596

color7 #AFC2B1
color15 #CAD8CB
