# vim:ft=kitty
## name: pinkfrog
## author: norm
## license: UPL-1.0
## blurb: A deep pink theme for kitty with bright readable text

# General
foreground                      #E8C4D2
background                      #26121B
selection_foreground            #26121B
selection_background            #B87592

# Cursor
cursor                          #E5A7BC
cursor_text_color               #26121B

# Links
url_color                       #F09ABB

# Borders
active_border_color             #B87592
inactive_border_color           #412330
bell_border_color               #C47A98
visual_bell_color               #C47A98

# Tabs
active_tab_foreground           #E8C4D2
active_tab_background           #26121B
inactive_tab_foreground         #A77A8D
inactive_tab_background         #341B26
tab_bar_background              #26121B
tab_bar_margin_color            #26121B

# Colors
color0 #26121B
color8 #654052

color1 #E06B8A
color9 #F18AA5

color2 #8DBB96
color10 #A9D5AE

color3 #D0AE72
color11 #E5C78E

color4 #8D91C0
color12 #AEB3E0

color5 #D477A7
color13 #F09AC4

color6 #83BDB3
color14 #A5D8CF

color7 #E8C4D2
color15 #F8E6ED
