# vim:ft=kitty
## name: bloodrite
## author: luna
## license: UPL-1.0
## blurb: Deep blood-red dark theme

# General
foreground                      #D8C6C9
background                      #120D10
selection_foreground            #F0DADD
selection_background            #7F101D

# Cursor
cursor                          #B51B2C
cursor_text_color               #120D10

# Links
url_color                       #C12A3A

# Borders
active_border_color             #A91628
inactive_border_color           #3B2027
bell_border_color               #B51B2C
visual_bell_color               #B51B2C

# Tabs
active_tab_foreground           #C72B3D
active_tab_background           #120D10
inactive_tab_foreground         #806A70
inactive_tab_background         #25161B
tab_bar_background              #0E0A0D
tab_bar_margin_color            #0E0A0D

# Colors
color0                          #120D10
color8                          #45262D

color1                          #A91628
color9                          #D02B3D

color2                          #667A69
color10                         #8DA58F

color3                          #8D604A
color11                         #B98768

color4                          #536079
color12                         #7B8DA8

color5                          #794653
color13                         #A85C6D

color6                          #526F70
color14                         #789999

color7                          #BBA8AC
color15                         #E8DADD
